PLUGIN_NAME=		api-extensions
PLUGIN_VERSION=	0.10
PLUGIN_COMMENT=		Additional API endpoints for system automation
PLUGIN_MAINTAINER=	ted.welch@biptec.com
PLUGIN_DEPENDS=		arping

.include "../../Mk/plugins.mk"
