#!/usr/local/bin/python3
import sys
sys.path.insert(0, "/usr/local/opnsense/scripts/OPNsense/ApiExtensions")

from carp_health import checker_exit_code, load_config, read_state

try:
    config = load_config()
    state = read_state()
    sys.exit(checker_exit_code(config, state))
except Exception:
    sys.exit(1)
